xpay: add regtest for blinded path fees
When the paying node is the entry point to the blinded path it will send
the wrong amount to the next peer. Instead of sending AMT_MSAT it will
send AMT_MSAT+FEES_MSAT.

        # we pay fees to ourselves
        htlcs = l1.rpc.listhtlcs()["htlcs"]
        assert len(htlcs) == 1
        assert htlcs[0]["payment_hash"] == b12_decode["invoice_payment_hash"]
>       assert htlcs[0]["amount_msat"] == AMT_MSAT
E       assert 15000 == 10000

Changelog-None

Signed-off-by: Lagrang3 <lagrang3@protonmail.com>